Update pr_develop.yaml

diff --git a/.pipelines/pr_develop.yaml b/.pipelines/pr_develop.yaml
--- a/.pipelines/pr_develop.yaml
+++ b/.pipelines/pr_develop.yaml
@@ -22,10 +22,31 @@ steps:
 - script: echo Hello, world!
   displayName: 'Run a one-line script'
 
+- script: 
+
 - script: |
     echo Add other tasks to build, test, and deploy your project.
     echo See https://aka.ms/yaml
   displayName: 'Run a multi-line script'
+
+- script: |
+  if ! command -v gcc &> /dev/null; then
+    echo "GCC hasn't installed."
+    if [ -x "$(command -v apt)" ]; then
+          echo "Installing GCC with apt..."
+          sudo apt update
+          sudo apt install -y gcc
+      elif [ -x "$(command -v yum)" ]; then
+          echo "Installing gcc with Yum..."
+          sudo yum update
+          sudo yum install -y gcc
+      else
+          echo "Cannot file gcc."
+          exit 1
+      fi
+    fi
+  echo "GCC has been installed."
+  displayName:'Install gcc'
 
 - script: |
     if ! command -v cppcheck &> /dev/null
