Running debug on track1

diff --git a/.pipelines/pr_develop - Copy.yaml b/.pipelines/pr_develop - Copy.yaml
--- a/.pipelines/pr_develop - Copy.yaml
+++ b/.pipelines/pr_develop - Copy.yaml
@@ -22,32 +22,24 @@ steps:
 - script: echo Hello, world!
   displayName: 'Run a one-line script'
 
-- script: 
-
 - script: |
     echo Add other tasks to build, test, and deploy your project.
     echo See https://aka.ms/yaml
   displayName: 'Run a multi-line script'
 
+#Installing GCC
 - script: |
-  if ! command -v gcc &> /dev/null; then
-    echo "GCC hasn't installed."
-    if [ -x "$(command -v apt)" ]; then
-          echo "Installing GCC with apt..."
-          sudo apt update
-          sudo apt install -y gcc
-      elif [ -x "$(command -v yum)" ]; then
-          echo "Installing gcc with Yum..."
-          sudo yum update
-          sudo yum install -y gcc
-      else
-          echo "Cannot file gcc."
-          exit 1
-      fi
+    if ! command -v gcc &> /dev/null
+    then
+      echo "GCC not found, installing..."
+      sudo apt update
+      sudo apt install -y gcc
+    else
+      echo "GCC already installed"
     fi
-  echo "GCC has been installed."
-  displayName:'Install gcc'
+  displayName: 'Install GCC'
 
+#Installing cppcheck
 - script: |
     if ! command -v cppcheck &> /dev/null
     then
@@ -59,8 +51,22 @@ steps:
     fi
   displayName: 'Install cppcheck'
 
+#Run cppcheck
 - script: |
     cppcheck --version
     cppcheck --enable=all ./src/track1/*.*
     cppcheck --enable=all ./src/track2/*.*
   displayName: 'Run cppcheck'
+
+- script: |
+    echo "Running gcc"
+    cd src/track1
+    gcc -o test test.c 2> error.log
+
+    if [ -s error.log ]; then
+        echo "Bugs found, check error.log for detail"
+    else
+        echo "There's no error"
+    fi
+      
+  displayName: 'Run GCC'
